// Generated by gencpp from file sawyer_beer/target.msg
// DO NOT EDIT!


#ifndef SAWYER_BEER_MESSAGE_TARGET_H
#define SAWYER_BEER_MESSAGE_TARGET_H

#include <ros/service_traits.h>


#include <sawyer_beer/targetRequest.h>
#include <sawyer_beer/targetResponse.h>


namespace sawyer_beer
{

struct target
{

typedef targetRequest Request;
typedef targetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct target
} // namespace sawyer_beer


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sawyer_beer::target > {
  static const char* value()
  {
    return "66e12f7d13e74171b48748f4e38919a7";
  }

  static const char* value(const ::sawyer_beer::target&) { return value(); }
};

template<>
struct DataType< ::sawyer_beer::target > {
  static const char* value()
  {
    return "sawyer_beer/target";
  }

  static const char* value(const ::sawyer_beer::target&) { return value(); }
};


// service_traits::MD5Sum< ::sawyer_beer::targetRequest> should match 
// service_traits::MD5Sum< ::sawyer_beer::target > 
template<>
struct MD5Sum< ::sawyer_beer::targetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sawyer_beer::target >::value();
  }
  static const char* value(const ::sawyer_beer::targetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sawyer_beer::targetRequest> should match 
// service_traits::DataType< ::sawyer_beer::target > 
template<>
struct DataType< ::sawyer_beer::targetRequest>
{
  static const char* value()
  {
    return DataType< ::sawyer_beer::target >::value();
  }
  static const char* value(const ::sawyer_beer::targetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sawyer_beer::targetResponse> should match 
// service_traits::MD5Sum< ::sawyer_beer::target > 
template<>
struct MD5Sum< ::sawyer_beer::targetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sawyer_beer::target >::value();
  }
  static const char* value(const ::sawyer_beer::targetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sawyer_beer::targetResponse> should match 
// service_traits::DataType< ::sawyer_beer::target > 
template<>
struct DataType< ::sawyer_beer::targetResponse>
{
  static const char* value()
  {
    return DataType< ::sawyer_beer::target >::value();
  }
  static const char* value(const ::sawyer_beer::targetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SAWYER_BEER_MESSAGE_TARGET_H
